### ISSUE TITLE
Testnet Difficulty Adjustment Broken

### ISSUE THREAD

**Issue by HashEngineering** [bitcoinj-cash/bitcoinj#7]
It was pointed out to me that my Bitcoin Cash Wallet app (for testnet) gets stuck at the November 13 hard fork.

In my bitcoincashj library, the difficulty adjustment algorithm for testnet does not work correctly.  Since this library is based my library, then bitcoinj-cash probably has the same problem.  I will work on a solution and submit it in the next week or so.

**Comment by rseibane** [comment]
I think this is a prior issue. What have to be done here?

**Comment by HashEngineering** [comment]
Fix the difficulty adjustment algorithm on testnet.  That may be the last change we do as we plan to transition to http://github.com/bitcoinj-cash/bitcoinj

**Comment by rseibane** [comment]
Yes, I found this issue coming from the bitcoinj-cash project :-)
I would like to help you out with this, but I get the impression I'm still noob, because I don't follow what makes the DAA different on testnet than mainnet. I'm trying to find out the difference. Meanwhile, if you can refer to any document or like that it's appreciated.
Thanks,

**Comment by rseibane** [comment]
PR to solve this in #8

**Comment by HashEngineering** [comment]
#8 resolved this issue for a short time.  However, after updating checkpoints in my app, it was discovered that the November 13 DAA doesn't work if difficulty checks start after November 12 (or 144 blocks before November 13) on the blockchain.  #18 was created to address this issue.  If checkpoints end before November 12, then there are no issues.

**Comment by HashEngineering** [comment]
All fixes have been merged.
