### ISSUE TITLE
support for bech32 addresses?

### ISSUE THREAD

**Issue by fireduck64** [bitcoinj-cash/bitcoinj#75]
I don't see a way to make an Address object from a bech32 address.

Ideally there would also be a method to get an address without caring which format it is in.

And a way to convert an address into a bech32 string.

I can add this but probably won't get to it for a while.

**Comment by HashEngineering** [comment]
I am thinking about copying the idea from bitcoinj;

abstract Address (base class)
  -- LegacyAddress
  -- CashAddress

Address would have a **fromString** method and it would create the correct object based on the given string.

For now we have `CashAddressFactory` that will create a `CashAddress` object from a string.

We are not using the bech32 nomenclature because the cashaddr format is somewhat different, though it uses the same encoding the hash160's.  What differs is the human readable part.

bech32:  bc1q.....
cashaddr:  bitcoincash:q...

**Comment by fireduck64** [comment]
Is CashAddressFactory a secret?  I can't find it anywhere.

**Comment by HashEngineering** [comment]
https://github.com/bitcoinj-cash/bitcoinj/blob/cash-0.14/core/src/main/java/org/bitcoinj/core/CashAddressFactory.java#L31

**Comment by fireduck64** [comment]
No idea how I didn't see that yesterday.  Thanks!
